<?php  
 $connect = mysqli_connect("localhost", "root", "", "mydb");  
 $query ="SELECT * FROM artist";  
 $result = mysqli_query($connect, $query);  
 ?>  

<html>
  <head>
    <body style='background-color:skyblue'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon PHP Framework</title>
    <?php echo $this->assets->outputCss('styles'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 
  </head>
    <body id="page-top" >
    <h3 align="center">ARTIST</h3> 

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary fixed-top text-uppercase" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">ART MUSEUM</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="views/index">Home</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#artobject">Art Object</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#collection">Collection</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#exhibtion">Exhibition</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#artist">Artist</a>
            </li>
          </ul>
           <ul class="navbar-nav  navbar-right">     
   	
    </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
  




 <!DOCTYPE html>  
 <html>
      <style>
      img{
        width: 200px ;
      }
      </style>  
      <head>  
           <title>ARTIST</title>  
           <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>  
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
           <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>  
           <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>            
           <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />  
      </head>  
      <body>  
           
           <div class="container">  
                
                 
                <div class="table-responsive">  
                     <table id="employee_data" class="table table-striped table-bordered">  
                          <thead>  
                               <tr>  
                                    <td>Picture</td>                                 
                                    <td>Name</td>   
                                    <td>Born</td>  
                                    <td>Died</td>  
                                    <td>Country</td>  
                                    <td>Epoch</td>
                                    <td>Style</td>
                                    <td>Description</td>   
 
                               </tr>  
                          </thead>  
                          <?php  
                          while($row = mysqli_fetch_array($result))  
                          {  
                               echo '  
                               <tr>                                      
                                    <td width = 100px>'."<img src=".$row['picture'].">".'</td>  
                                    <td>'.$row["name"].'</td>  
                                    <td>'.$row["date_born"].'</td>  
                                    <td>'.$row["date_died"].'</td>  
                                    <td>'.$row["country"].'</td>  
                                    <td>'.$row["epoch"].'</td>
                                    <td>'.$row["main_style"].'</td>  
                                    <td>'.$row["description"].'</td>   

                               </tr>  
                               ';  
                          }  
                          ?>  
                     </table>  
                </div>  
           </div>  
      </body>  
 </html>  
 <script>  
 $(document).ready(function(){  
      $('#employee_data').DataTable();  
 });  
 </script>  